spring:
  application:
    name: consume
  profiles:
    active: dev
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8087/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream